spring:
  liquibase:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  r2dbc:
    url: r2dbc:postgresql://localhost:5434/user_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: user-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual_immediate
      concurrency: 1
      missing-topics-fatal: false
      poll-timeout: 3000

logging:
  level:
    liquibase: DEBUG
  file:
    name: logs/app.log      # файл для Promtail/Loki


minio:
  url: http://localhost:9000
  access-key: ${ACCESS_KEY}
  secret-key: ${SECRET_KEY}
  bucket: ${BUCKET}

server:
  port: 8082
