server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    #    url: jdbc:postgresql://localhost:5432/auth_service_db
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/auth_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  jwt:
    access:
      private: ${JWT_ACCESS_PRIVATE_PATH:classpath:config/jwt/access_private.pem}
      public: ${JWT_ACCESS_PUBLIC_PATH:classpath:config/jwt/access_public.pem}
      expiration: 3600000
    refresh:
      private: ${JWT_REFRESH_PRIVATE_PATH:classpath:config/jwt/refresh_private.pem}
      public: ${JWT_REFRESH_PUBLIC_PATH:classpath:config/jwt/refresh_public.pem}
      expiration: 604800000

  mail:
    host: smtp.gmail.com
    port: 587
    username: simple.taxiofficial@gmail.com
    password: ${EMAIL_PASSWORD:123}   # пароль приложения из Google
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp
    debug: true

  data:
    redis:
      host: localhost
      port: 6379


  kafka:
    topics:
      user-registration: user-saga-topic
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

google:
  app: ${GOOGLE_APP_NAME:SimpleTaxiAuth}
  client-id: ${GOOGLE_CLIENT_ID:123}
  client-secret: ${GOOGLE_CLIENT_SECRET:123}
  token-uri: https://oauth2.googleapis.com/token

logging:
  level:
    org.springframework.web: ${REST_LOG_LEVEL:TRACE}
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

dev:
  email:
    verification: false
