server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: springboot-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: springboot
          __path__: /logs/*.log

    pipeline_stages:
      - regex:
          expression: '^(?P<ts>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}[+-]\d{2}:\d{2}) (?P<level>\S+) \S+ --- \[(?P<thread>[^\]]+)\] (?P<component>\S+) +: (?P<msg>.*)$'
      - labels:
          level: ""
          component: ""

